name: leam

services:
  model:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    networks:
      - net
    expose:
      - "8000"

  nginx:
    image: nginx:1.29.3-alpine-slim
    container_name: ngx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - net
    depends_on:
      - model

networks:
  net:
    driver: bridge